### ISSUE TITLE
CSS Library

### ISSUE THREAD

**Issue by pheara** [Haskell-Praxis/hakyll-cms#2]
We might want to use an existing css-library to speed up styling.

Some alternatives:
* bootstrap
* semantic-ui
* tachyons
* [reflex-frp-semui](https://github.com/reflex-frp/reflex-dom-semui)
* something like elm-bootstrap but for reflex
* ...

Also interesting for own styles might be libraries along the lines of elm-styles/-css.

**Comment by peacememories** [comment]
Since semantic ui looks very usable and has an existing reflex-dom wrapper I suggest we use it.
